name: room_rental_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8
  get: ^4.6.6
  flutter_map: ^7.0.2
  http: ^1.2.2
  latlong2: ^0.9.1
  flutter_slidable: ^3.1.1
  smooth_page_indicator: ^1.1.0
  flutter_launcher_icons: ^0.14.1
  photo_view: ^0.15.0
  google_maps_flutter: ^2.9.0
  permission_handler: ^11.3.1
  table_calendar: ^3.1.2
  flutter_native_splash: ^2.4.3
  font_awesome_flutter: ^10.8.0
  flutter_google_places_hoc081098: ^2.0.0
  persistent_bottom_nav_bar: ^6.2.1
  flutter_svg: ^2.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.14.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/sangkaestay.png"

flutter_native_splash:  
  android: true
  ios: true
  web: false

  background_image: "assets/images/background.png"
  image: "assets/images/logo.png"
  branding: "assets/images/name_no_bg.png"

  android_12:
    background_image: "assets/images/background.png"
    image: "assets/images/logo.png"
    branding: "assets/images/name_no_bg.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/sangkaestay.png
    - assets/images/room.jpg
    - assets/images/logo_blue.svg
  fonts:
    - family: NotoSansKhmer
      fonts:
        - asset: assets/fonts/NotoSansKhmer-Regular.ttf